name: Preview tests

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  preview-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build and start compose services
        run: |
          # Use the CI compose file (the README suggests docker-compose.ci.yml)
          docker compose -f docker-compose.ci.yml up -d --build

      - name: Run backend pytest inside backend container
        run: docker compose exec -T backend pytest -q

      - name: Tear down compose
        if: always()
        run: docker compose -f docker-compose.ci.yml down --remove-orphans
