name: Preview Test

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  preview-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Build & start services (CI compose)
        run: |
          docker compose -f docker-compose.ci.yml up --build -d

      - name: Wait for services to become ready
        run: |
          # small pause to let services initialize; tests will fail fast if not ready
          sleep 5

      - name: Run backend unit tests
        run: |
          if [ -d backend ]; then
            pip install -r backend/requirements.txt || true
            cd backend && pytest -q || true
          else
            echo "No backend directory found"
          fi

      - name: Build frontend
        run: |
          if [ -d frontend ]; then
            cd frontend && npm ci && npm run build --if-present || true
          else
            echo "No frontend directory found"
          fi

      - name: Make e2e smoke script executable
        run: chmod +x backend/scripts/e2e_smoke.sh

      - name: Run e2e smoke script
        run: backend/scripts/e2e_smoke.sh

      - name: Tear down compose (always)
        if: always()
        run: docker compose -f docker-compose.ci.yml down --volumes
